// Catálogo de candidatos. El título en español es el que se busca en FilmAffinity;
// el original es el que se busca en TMDB. Si alguno no resuelve, se descarta y se
// avisa: preferimos 90 títulos correctos a 100 con datos inventados.

module.exports = [
  // ── UCM · Marvel Studios ────────────────────────────────────────────────
  { es: 'Iron Man', orig: 'Iron Man', anio: 2008, tipo: 'pelicula', universo: 'UCM' },
  { es: 'El increíble Hulk', orig: 'The Incredible Hulk', anio: 2008, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Iron Man 2', orig: 'Iron Man 2', anio: 2010, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Thor', orig: 'Thor', anio: 2011, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Capitán América: El primer vengador', orig: 'Captain America: The First Avenger', anio: 2011, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Los Vengadores', orig: 'The Avengers', anio: 2012, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Iron Man 3', orig: 'Iron Man 3', anio: 2013, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Thor: El mundo oscuro', orig: 'Thor: The Dark World', anio: 2013, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Capitán América: El soldado de invierno', orig: 'Captain America: The Winter Soldier', anio: 2014, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Guardianes de la Galaxia', orig: 'Guardians of the Galaxy', anio: 2014, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Vengadores: La era de Ultrón', orig: 'Avengers: Age of Ultron', anio: 2015, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Ant-Man: El hombre hormiga', orig: 'Ant-Man', anio: 2015, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Capitán América: Civil War', orig: 'Captain America: Civil War', anio: 2016, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Doctor Strange (Doctor Extraño)', orig: 'Doctor Strange', anio: 2016, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Guardianes de la Galaxia Vol. 2', orig: 'Guardians of the Galaxy Vol. 2', anio: 2017, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Spider-Man: Homecoming', orig: 'Spider-Man: Homecoming', anio: 2017, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Thor: Ragnarok', orig: 'Thor: Ragnarok', anio: 2017, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Black Panther', orig: 'Black Panther', anio: 2018, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Vengadores: Infinity War', orig: 'Avengers: Infinity War', anio: 2018, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Ant-Man y la Avispa', orig: 'Ant-Man and the Wasp', anio: 2018, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Capitana Marvel', orig: 'Captain Marvel', anio: 2019, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Vengadores: Endgame', orig: 'Avengers: Endgame', anio: 2019, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Spider-Man: Lejos de casa', orig: 'Spider-Man: Far from Home', anio: 2019, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Viuda negra', orig: 'Black Widow', anio: 2021, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Shang-Chi y la leyenda de los Diez Anillos', orig: 'Shang-Chi and the Legend of the Ten Rings', anio: 2021, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Eternals', orig: 'Eternals', anio: 2021, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Spider-Man: No Way Home', orig: 'Spider-Man: No Way Home', anio: 2021, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Doctor Strange en el multiverso de la locura', orig: 'Doctor Strange in the Multiverse of Madness', anio: 2022, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Thor: Love and Thunder', orig: 'Thor: Love and Thunder', anio: 2022, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Black Panther: Wakanda Forever', orig: 'Black Panther: Wakanda Forever', anio: 2022, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Ant-Man y la Avispa: Quantumanía', orig: 'Ant-Man and the Wasp: Quantumania', anio: 2023, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Guardianes de la Galaxia Vol. 3', orig: 'Guardians of the Galaxy Vol. 3', anio: 2023, tipo: 'pelicula', universo: 'UCM' },
  { es: 'The Marvels', orig: 'The Marvels', anio: 2023, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Deadpool y Lobezno', orig: 'Deadpool & Wolverine', anio: 2024, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Capitán América: Brave New World', orig: 'Captain America: Brave New World', anio: 2025, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Thunderbolts*', orig: 'Thunderbolts*', anio: 2025, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Los Cuatro Fantásticos: Primeros pasos', orig: 'The Fantastic Four: First Steps', anio: 2025, tipo: 'pelicula', universo: 'UCM' },
  { es: 'Spider-Man: Brand New Day', orig: 'Spider-Man: Brand New Day', anio: 2026, tipo: 'pelicula', universo: 'UCM' },

  // ── Fox ─────────────────────────────────────────────────────────────────
  { es: 'X-Men', orig: 'X-Men', anio: 2000, tipo: 'pelicula', universo: 'Fox' },
  { es: 'X-Men 2', orig: 'X2', anio: 2003, tipo: 'pelicula', universo: 'Fox' },
  { es: 'X-Men: La decisión final', orig: 'X-Men: The Last Stand', anio: 2006, tipo: 'pelicula', universo: 'Fox' },
  { es: 'X-Men orígenes: Lobezno', orig: 'X-Men Origins: Wolverine', anio: 2009, tipo: 'pelicula', universo: 'Fox' },
  { es: 'X-Men: Primera generación', orig: 'X-Men: First Class', anio: 2011, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Lobezno inmortal', orig: 'The Wolverine', anio: 2013, tipo: 'pelicula', universo: 'Fox' },
  { es: 'X-Men: Días del futuro pasado', orig: 'X-Men: Days of Future Past', anio: 2014, tipo: 'pelicula', universo: 'Fox' },
  { es: 'X-Men: Apocalipsis', orig: 'X-Men: Apocalypse', anio: 2016, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Deadpool', orig: 'Deadpool', anio: 2016, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Logan', orig: 'Logan', anio: 2017, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Deadpool 2', orig: 'Deadpool 2', anio: 2018, tipo: 'pelicula', universo: 'Fox' },
  { es: 'X-Men: Fénix Oscura', orig: 'Dark Phoenix', anio: 2019, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Los nuevos mutantes', orig: 'The New Mutants', anio: 2020, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Los 4 Fantásticos', orig: 'Fantastic Four', anio: 2005, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Los 4 Fantásticos y Silver Surfer', orig: 'Fantastic Four: Rise of the Silver Surfer', anio: 2007, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Cuatro Fantásticos', orig: 'Fantastic Four', anio: 2015, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Daredevil', orig: 'Daredevil', anio: 2003, tipo: 'pelicula', universo: 'Fox' },
  { es: 'Elektra', orig: 'Elektra', anio: 2005, tipo: 'pelicula', universo: 'Fox' },

  // ── Sony ────────────────────────────────────────────────────────────────
  { es: 'Spider-Man', orig: 'Spider-Man', anio: 2002, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Spider-Man 2', orig: 'Spider-Man 2', anio: 2004, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Spider-Man 3', orig: 'Spider-Man 3', anio: 2007, tipo: 'pelicula', universo: 'Sony' },
  { es: 'The Amazing Spider-Man', orig: 'The Amazing Spider-Man', anio: 2012, tipo: 'pelicula', universo: 'Sony' },
  { es: 'The Amazing Spider-Man 2: El poder de Electro', orig: 'The Amazing Spider-Man 2', anio: 2014, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Spider-Man: Un nuevo universo', orig: 'Spider-Man: Into the Spider-Verse', anio: 2018, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Spider-Man: Cruzando el multiverso', orig: 'Spider-Man: Across the Spider-Verse', anio: 2023, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Venom', orig: 'Venom', anio: 2018, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Venom: Habrá matanza', orig: 'Venom: Let There Be Carnage', anio: 2021, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Venom: El último baile', orig: 'Venom: The Last Dance', anio: 2024, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Morbius', orig: 'Morbius', anio: 2022, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Madame Web', orig: 'Madame Web', anio: 2024, tipo: 'pelicula', universo: 'Sony' },
  { es: 'Kraven el cazador', orig: 'Kraven the Hunter', anio: 2024, tipo: 'pelicula', universo: 'Sony' },

  // ── Antiguas y sueltas ──────────────────────────────────────────────────
  { es: 'Howard, un nuevo héroe', orig: 'Howard the Duck', anio: 1986, tipo: 'pelicula', universo: 'Clásicos' },
  { es: 'Blade', orig: 'Blade', anio: 1998, tipo: 'pelicula', universo: 'Clásicos' },
  { es: 'Blade II', orig: 'Blade II', anio: 2002, tipo: 'pelicula', universo: 'Clásicos' },
  { es: 'Blade: Trinity', orig: 'Blade: Trinity', anio: 2004, tipo: 'pelicula', universo: 'Clásicos' },
  { es: 'Hulk', orig: 'Hulk', anio: 2003, tipo: 'pelicula', universo: 'Clásicos' },
  { es: 'El castigador', orig: 'The Punisher', anio: 2004, tipo: 'pelicula', universo: 'Clásicos' },
  { es: 'Punisher: Zona de guerra', orig: 'Punisher: War Zone', anio: 2008, tipo: 'pelicula', universo: 'Clásicos' },
  { es: 'Ghost Rider: El motorista fantasma', orig: 'Ghost Rider', anio: 2007, tipo: 'pelicula', universo: 'Clásicos' },
  { es: 'Ghost Rider: Espíritu de venganza', orig: 'Ghost Rider: Spirit of Vengeance', anio: 2011, tipo: 'pelicula', universo: 'Clásicos' },

  // ── Series ──────────────────────────────────────────────────────────────
  { es: 'Daredevil', orig: 'Daredevil', anio: 2015, tipo: 'serie', universo: 'Netflix' },
  { es: 'Jessica Jones', orig: 'Jessica Jones', anio: 2015, tipo: 'serie', universo: 'Netflix' },
  { es: 'Luke Cage', orig: 'Luke Cage', anio: 2016, tipo: 'serie', universo: 'Netflix' },
  { es: 'Iron Fist', orig: 'Iron Fist', anio: 2017, tipo: 'serie', universo: 'Netflix' },
  { es: 'The Defenders', orig: 'The Defenders', anio: 2017, tipo: 'serie', universo: 'Netflix' },
  { es: 'The Punisher', orig: 'The Punisher', anio: 2017, tipo: 'serie', universo: 'Netflix' },
  { es: 'Bruja Escarlata y Visión', orig: 'WandaVision', anio: 2021, tipo: 'serie', universo: 'Disney+' },
  { es: 'Falcon y el Soldado de Invierno', orig: 'The Falcon and the Winter Soldier', anio: 2021, tipo: 'serie', universo: 'Disney+' },
  { es: 'Loki', orig: 'Loki', anio: 2021, tipo: 'serie', universo: 'Disney+' },
  { es: '¿Qué pasaría si...?', orig: 'What If...?', anio: 2021, tipo: 'serie', universo: 'Disney+' },
  { es: 'Ojo de Halcón', orig: 'Hawkeye', anio: 2021, tipo: 'serie', universo: 'Disney+' },
  { es: 'Caballero Luna', orig: 'Moon Knight', anio: 2022, tipo: 'serie', universo: 'Disney+' },
  { es: 'Ms. Marvel', orig: 'Ms. Marvel', anio: 2022, tipo: 'serie', universo: 'Disney+' },
  { es: 'She-Hulk: Abogada Hulka', orig: 'She-Hulk: Attorney at Law', anio: 2022, tipo: 'serie', universo: 'Disney+' },
  { es: 'Secret Invasion', orig: 'Secret Invasion', anio: 2023, tipo: 'serie', universo: 'Disney+' },
  { es: 'Echo', orig: 'Echo', anio: 2024, tipo: 'serie', universo: 'Disney+' },
  { es: 'X-Men 97', orig: "X-Men '97", anio: 2024, tipo: 'serie', universo: 'Disney+' },
  { es: 'Agatha, ¿quién si no?', orig: 'Agatha All Along', anio: 2024, tipo: 'serie', universo: 'Disney+' },
  { es: 'Daredevil: Born Again', orig: 'Daredevil: Born Again', anio: 2025, tipo: 'serie', universo: 'Disney+' },
  { es: 'Ironheart', orig: 'Ironheart', anio: 2025, tipo: 'serie', universo: 'Disney+' },
  { es: 'Marvel Agents of S.H.I.E.L.D.', orig: 'Agents of S.H.I.E.L.D.', anio: 2013, tipo: 'serie', universo: 'TV' },
  { es: 'Agente Carter', orig: 'Agent Carter', anio: 2015, tipo: 'serie', universo: 'TV' },
  { es: 'Inhumans', orig: 'Inhumans', anio: 2017, tipo: 'serie', universo: 'TV' },
  { es: 'Legión', orig: 'Legion', anio: 2017, tipo: 'serie', universo: 'TV' },
  { es: 'Runaways', orig: 'Runaways', anio: 2017, tipo: 'serie', universo: 'TV' },
  { es: 'Cloak & Dagger', orig: 'Cloak & Dagger', anio: 2018, tipo: 'serie', universo: 'TV' },
  { es: 'The Gifted', orig: 'The Gifted', anio: 2017, tipo: 'serie', universo: 'TV' }
];
